import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from './providers'

export const metadata = {
  title: "Cardapia",
  description: "Generated by create next app",
  icons: {
    icon: "/imagens/comida.png",
  },
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], 
  variable: "--font-poppins", 
});

export default function RootLayout({ children }) {

  return (
    <html lang="pt-br">
      <body className={`${poppins.variable} font-sans`}>
          <Providers>
            {children}
         </Providers>
      </body>
    </html>
  );
}
